WIP: CMake: Link test-utils against Maliit::Plugins
Fixes errors such as the following due to missing /usr/include/maliit-2
(maliit-framework) include directory:

  /usr/lib/ccache/bin/g++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_TESTCASE_BUILDDIR=\"/builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835/build\" -DQT_TESTLIB_LIB -I/builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835/build -I/builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835 -I/builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835/build/test-utils_autogen/include -I /usr/include/qt5 -I /usr/include/qt5/QtCore -I /usr/lib/qt5/mkspecs/linux-g++ -I /usr/include/qt5/QtGui -I /usr/include/qt5/QtTest -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -fdebug-prefix-map=/builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835=. -fPIC -MD -MT CMakeFiles/test-utils.dir/tests/unittests/common/inputmethodhostprobe.cpp.o -MF CMakeFiles/test-utils.dir/tests/unittests/common/inputmethodhostprobe.cpp.o.d -o CMakeFiles/test-utils.dir/tests/unittests/common/inputmethodhostprobe.cpp.o -c /builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835/tests/unittests/common/inputmethodhostprobe.cpp
  In file included from /builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835/tests/unittests/common/inputmethodhostprobe.cpp:32:
  /builddir/keyboard-4c07f7a2f35f277860208f1f50b9a48acdbd5835/tests/unittests/common/inputmethodhostprobe.h:35:10: fatal error: maliit/plugins/abstractinputmethodhost.h: No such file or directory
     35 | #include <maliit/plugins/abstractinputmethodhost.h>
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~