CMake: Fix unittests QApplication include error
This is a part of Qt5::Widgets, so look for that and link against it.

  /usr/lib/ccache/bin/g++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_TESTCASE_BUILDDIR=\"/builddir/keyboard-2.2.1.1/build\" -DQT_TESTLIB_LIB -I/builddir/keyboard-2.2.1.1/build -I/builddir/keyboard-2.2.1.1 -I/builddir/keyboard-2.2.1.1/build/test-utils_autogen/include -I /usr/include/qt5 -I /usr/include/qt5/QtCore -I /usr/lib/qt5/mkspecs/linux-g++ -I /usr/include/qt5/QtGui -I /usr/include/qt5/QtTest -DNDEBUG -fstack-clash-protection -D_FORTIFY_SOURCE=2 -mtune=generic -O2    -fdebug-prefix-map=/builddir/keyboard-2.2.1.1=. -fPIC -MD -MT CMakeFiles/test-utils.dir/tests/unittests/common/utils-gui.cpp.o -MF CMakeFiles/test-utils.dir/tests/unittests/common/utils-gui.cpp.o.d -o CMakeFiles/test-utils.dir/tests/unittests/common/utils-gui.cpp.o -c /builddir/keyboard-2.2.1.1/tests/unittests/common/utils-gui.cpp
  /builddir/keyboard-2.2.1.1/tests/unittests/common/utils-gui.cpp:36:10: fatal error: QApplication: No such file or directory
     36 | #include <QApplication>
        |          ^~~~~~~~~~~~~~